--INNER JOIN KULLANIMI
--SELECT * FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER
--ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--LEFT JOIN KULLANIMI
--SELECT * FROM TBLNOTLAR
--LEFT JOIN TBLOGRENCILER
--ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--RIGHT JOIN KULLANIMI
--SELECT * FROM TBLNOTLAR
--RIGHT JOIN TBLOGRENCILER
--ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--FULL JOIN KULLANIMI
--SELECT * FROM TBLNOTLAR
--FULL JOIN TBLOGRENCILER
--ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--UNION
SELECT * FROM TBLKULUPLER UNION SELECT * FROM TBLDERSLER
--SELECT * FROM TBLDERSLER UNION SELECT * FROM TBLKULUPLER