--DDL KOMUTLARI GENEL TEKRAR
--DB --> Müþteri, Ürün, Personel, Kategori, Satýþ
--CREATE DATABASE SatisVT
--USE SatisVT

--CREATE TABLE TBLKATEGORI
--(
--KATEGORIID tinyint identity(1,1) primary key,
--KATEGORIAD varchar(50)
--)

--CREATE TABLE TBLURUNLER
--(
--URUNID int identity(1,1) primary key,
--URUNAD varchar(50),
--URUNMARKA varchar(50),
--KATEGORI tinyint,
--URUNALISFIYAT decimal(18,2),
--URUNSATISFIYAT decimal(18,2),
--URUNSTOK smallint check(URUNSTOK>0),
--URUNDURUM bit default '1'
--)

--CREATE TABLE TBLPERSONEL
--(
--PERSONELID smallint identity(1,1) primary key,
--PERSONELADSOYAD varchar(50)
--)

--CREATE TABLE TBLMUSTERI
--(
--MUSTERIID int identity(1,1) primary key,
--MUSTERIAD varchar(50),
--MUSTERISOYAD varchar(50),
--MUSTERISEHIR varchar(14),
--MUSTERIBAKIYE decimal(18,2)
--)

--CREATE TABLE TBLHAREKET
--(
--HAREKETID int primary key identity(1,1),
--URUN int,
--MUSTERI int,
--PERSONEL smallint,
--ADET int,
--TUTAR decimal(18,2),
--TARIH smalldatetime
--)

--TRUNCATE TABLE TBLURUNLER

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')

--INSERT INTO TBLURUNLER (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK) 
--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)

--SELECT * FROM TBLURUNLER

--UPDATE TBLURUNLER SET URUNAD = 'SU ISITICI' WHERE URUNAD = 'KETTLE'

--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' FROM TBLURUNLER 
--INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID
--GROUP BY KATEGORIAD ORDER BY COUNT(*)

--KATEGORÝ ADI BÝLGÝSAYAR OLAN ÜRÜNLERÝ SATIÞ FÝYATINA 500 TL ZAM YAPALIM...
--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'BÝLGÝSAYAR')
--SELECT * FROM TBLURUNLER

--TV KATEGORÝSÝNDEKÝ ÜRÜNLERÝN SATIÞ FÝYATINDA YÜZDE 10 ÝNDÝRÝM YAPAN SORGUYU YAZIN.
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT - URUNSATISFIYAT * 0.10 
--WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'TV')

--SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN', SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER
--SELECT * FROM TBLURUNLER

--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
--(URUNSATISFIYAT - URUNALISFIYAT) AS 'KAR',
--(URUNSATISFIYAT - URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR' FROM TBLURUNLER
--INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID

--TOPLAM KARI 1000 LÝRANIN ALTINDA KALAN ÜRÜNLERÝ SATIÞ FÝYATINA YÜZDE 20 ZAM YAPAN SORGU
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT + URUNSATISFIYAT * 0.20
--WHERE (URUNSATISFIYAT - URUNALISFIYAT) * URUNSTOK < 1000