--CREATE TABLE TBLDERSLER
--(
--DERSID tinyint,
--DERSAD varchar(20)
--)

--ALTER TABLE TBLDERSLER
--ADD KONTENJAN smallint

--ALTER TABLE TBLDERSLER
--DROP COLUMN KONTENJAN

--SELECT * FROM TBLOGRENCILER
--SELECT OGRAD,OGRSOYAD FROM TBLOGRENCILER
--SELECT OGRSEHIR FROM TBLOGRENCILER

--SELECT * FROM TBLOGRENCILER WHERE OGRAD = 'Ali'

--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR = 'Adana' AND OGRKULUP = 'Kitaplýk'
--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR = 'Adana' OR OGRKULUP = 'Satranç'

--Decimal(x,y)
--x: Virgülden Önce Basamak Sayýsý
--y: Virgülden Sonra Basamak Sayýsý
--Ortalama: 78,65 ** 100,00
--Decimal(5,2)

--SELECT * FROM TBLNOTLAR
--SELECT (SINAV1+SINAV2+SINAV3)/3 FROM TBLNOTLAR

--INSERT INTO TBLOGRENCILER (OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('Baran','Yücedað','Elazýð')	
--SELECT * FROM TBLOGRENCILER

--INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV3) VALUES (6,2,88,67)
--SELECT * FROM TBLNOTLAR

--DELETE FROM TBLDERSLER WHERE DERSID = 6
--DELETE FROM TBLDERSLER WHERE DERSAD = 'Algoritma'

--TRUNCATE TABLE TBLDERSLER

--UPDATE TBLOGRENCILER SET OGRCINSIYET = 'Kýz' WHERE OGRID=2
--UPDATE TBLOGRENCILER SET OGRCINSIYET = 'Kýz' WHERE OGRID=4 OR OGRID=5

--UPDATE TBLOGRENCILER SET OGRKULUP = 'Kitaplýk' WHERE OGRAD = 'Baran'

--UPDATE TBLNOTLAR SET DERS = 2

--INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV2) VALUES (5,2,78,66)

--UPDATE TBLNOTLAR SET ORTALAMA = (SINAV1+SINAV2+SINAV3)/3

--UPDATE TBLNOTLAR SET DURUM = 1 WHERE ORTALAMA >= 50
UPDATE TBLNOTLAR SET DURUM = 0 WHERE ORTALAMA < 50