--FONKSÝYON OLUÞTURMA

--CREATE FUNCTION STOKARTTIR(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @ADET+26
--END
--SELECT AD,STOK,DBO.STOKARTTIR(STOK) FROM TBLURUN

--ÖDEV: BÝR FONKSÝYON OLUÞTURULACAK. BU FONKSÝYON STOÐUN KAREKÖKÜNÜ ALACAK, ALMIÞ OLDUÐU BU KAREKÖKÜ 3 ÝLE ÇARPACAK.

--CREATE FUNCTION STOKKAREKOK(@STOK INT)
--RETURNS FLOAT
--AS
--BEGIN
--RETURN (SQRT(@STOK) * 3)
--END
--SELECT AD,STOK,DBO.STOKKAREKOK(STOK) FROM TBLURUN

--STRING TÜRDE FONKSÝYON OLUÞTURMA
--CREATE FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR
--ALTER FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END

--SELECT dbo.KUCUKHARF(AD),STOK FROM TBLURUN

--KDV FONKSÝYONU
--CREATE FUNCTION KDV(@FIYAT DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @FIYAT * 1.18
--END
--SELECT AD,SATISFIYAT,dbo.KDV(SATISFIYAT) AS 'KDVLÝ HALÝ' FROM TBLURUN

--TABLO SONUÇLU FONKSÝYONLAR
--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE URUNID = @URID
--SELECT * FROM dbo.URUNBILGI(4)

--ÖDEV: STOK SAYISINI GÝRDÝÐÝNÝZ ZAMAN BU STOK SAYISININ ALTINDA OLAN ÜRÜNLERÝ GETÝREN FONKSÝYONU YAZIN.
--CREATE FUNCTION STOKSAYISIALTI(@SAYI INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE STOK <= @SAYI
--SELECT * FROM dbo.STOKSAYISIALTI(50)
