--UPDATE TBLOGRENCILER SET OGRKULUP=1 WHERE OGRKULUP='Biliþim'
--UPDATE TBLOGRENCILER SET OGRKULUP=2 WHERE OGRKULUP='Kitaplýk'
--UPDATE TBLOGRENCILER SET OGRKULUP=3 WHERE OGRKULUP='Satranç'
--UPDATE TBLOGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'

--INSERT INTO TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('Berna',4,'Ankara')

--SELECT NOTID,DERSAD FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,OGRAD+ ' ' +OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR 
--INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--Ödev: Az önceki örnekten faydalanarak Durum 1 olanlarý Geçti, 0 olanlarý Kaldý yazsýn.
--SELECT NOTID,OGRAD+' '+OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,
--CASE WHEN DURUM = 1 THEN 'Geçti' ELSE 'Kaldý' END AS 'SONUÇ' FROM TBLNOTLAR
--INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--SELECT * FROM TBLNOTLAR
--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1
--UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA >= 50
--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA < 50

--Dersler tablosunda ismi matematik olan derse ait sýnav not bilgisi
-- SUB QUERY
--SELECT * FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Matematik')

--Dersler tablosunda ismi algoritma olan notlar tablosundaki algoritma dersine ait en yüksek sýnav1'i getiren sorgu
--SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')
-- Daha kapsamlý örnek
SELECT NOTID,OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1 AS 'En yüksek SINAV1 notu' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE SINAV1 = (SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='Algoritma'))