--PROSEDÜR KULLANIMI

--CREATE PROCEDURE HAREKETLER
--AS
--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD 'AD SOYAD',PERSONELADSOYAD,ADET,TUTAR,TARIH FROM TBLHAREKET 
--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN = TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI = TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL = TBLPERSONEL.PERSONELID

--EXECUTE HAREKETLER

--PROSEDÜR SÝLME VE GÜNCELLEME (DROP & AFTER)
--CREATE PROCEDURE DENEME
--AS
--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10
--EXEC DENEME
--DROP PROCEDURE DENEME

--ALTER PROCEDURE [dbo].[HAREKETLER]
--AS
--SELECT HAREKETID,URUNAD,LEFT(MUSTERIAD,1) + '. ' + MUSTERISOYAD 'AD SOYAD',PERSONELADSOYAD,ADET,TUTAR,TARIH FROM TBLHAREKET 
--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN = TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI = TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL = TBLPERSONEL.PERSONELID
--EXEC HAREKETLER

--PARAMETRELÝ PROSEDÜR KULLANIMI
--ALTER PROCEDURE URUNGETIR
--@Deger varchar(50)='BUZDOLABI'
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNAD=@Deger

--EXECUTE URUNGETIR @Deger = 'LAPTOP'

--STOK SAYISI DIÞARIDAN GÝRÝLEN 10'DAN BÜYÜK OLANLARI GETÝREN PROSEDÜRÜ YAZIN.
CREATE PROCEDURE DERS46ODEV
@Deger smallint = 0
AS
SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK,URUNDURUM
FROM TBLURUNLER INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID
WHERE URUNSTOK > @DEGER
EXECUTE DERS46ODEV @Deger = 9