--SELECT 20 + 4 AS 'Toplam', 20 - 4 AS 'Fark', 20 * 4 AS 'Çarpým', 20 / 4 AS 'Bölüm'

--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE Ders = 1
--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100
--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--SELECT AVG(Ortalama) FROM TBLNOTLAR WHERE Ders = 1

-- Sýnýf ortalamasýnýn altýnda olan öðrencilerin "Durum2" sütunlarýnýn yanýna "Altýnda", aksi durumda "Üstünde" yazdýran sorguyu hazýrlayýn...
--SELECT OGRID, OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERS, ORTALAMA, 'Altýnda' AS 'Durum 2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
--WHERE ORTALAMA < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS IN (1,2)
--UNION
--SELECT OGRID, OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERS, ORTALAMA, 'Üstünde' AS 'Durum 2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
--WHERE ORTALAMA > (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS IN (1,2)

--MATEMATÝKSEL FONKSÝYONLAR

--SELECT * FROM TBLNOTLAR
--ABS
--SELECT ABS(-85) AS 'MUTLAK'
--SELECT POWER(2,4) AS 'ÜS ALMA'

--SELECT POWER(SINAV1,2) FROM TBLNOTLAR

--SELECT SQRT(625) AS 'KAREKÖK'

--SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'

--AVG VE SUM FONKSÝYONLARI
--SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1
--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

--SELECT DERSAD,SINAV1 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID WHERE OGRENCI=1

--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayþe' AND OGRSOYAD = 'Çýnar')

--SELECT SUM(SINAV1),AVG(SINAV1) FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayþe' AND OGRSOYAD = 'Çýnar')

--Ayþe Çýnar'ýn Algoritma dersinde almýþ olduðu 1. sýnav notunun sýnýf ortalamasýnýn üstünde mi yoksa altýnda mý olan sorguyu yapýnýz.
SELECT OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERSAD, SINAV1, 'Üstünde' AS 'Durum' FROM TBLNOTLAR 
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayþe' AND OGRSOYAD = 'Çýnar')
AND SINAV1 >= (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')
UNION
SELECT OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERSAD, SINAV1, 'Altýnda' AS 'Durum' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayþe' AND OGRSOYAD = 'Çýnar')
AND SINAV1 < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')

