--ÖRNEK DATAPART SORGULARI
--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND MUSTERI = 1

--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND 
--MUSTERI = (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'Ankara')

--DATENAME FONKSÝYONU
--SELECT DATENAME(MONTH,getdate()),datename(MONTH,'2019.01.15')
--SELECT DATENAME(WEEKDAY,GETDATE())
--SELECT DATENAME(WEEKDAY,'2019.06.10')

--DATEDIFF FONKSÝYONU
--SELECT DATEDIFF(YEAR,'2010.10.25',GETDATE())
--SELECT DATEDIFF(MONTH,'2010.06.14','2015.08.06')
--SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID = 1

--DATEADD FONKSÝYONU
--SELECT DATEADD(YEAR,3,'2009-10-25')
--SELECT DATEADD(DAY,45,GETDATE())
--SELECT DATEADD(MONTH,350,GETDATE())