--CREATE DATABASE DbYeni
--USE DbYeni

--CREATE TABLE TBLMUSTERI
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--SOYAD VARCHAR(20),
--SEHIR VARCHAR(15),
--BAKIYE DECIMAL(18,2)
--)

--CREATE TABLE TBLKATEGORI
--(
--KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20)
--)

--CREATE TABLE TBLURUN
--(
--URUNID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--ALISFIYAT DECIMAL(18,2),
--SATISFIYAT DECIMAL(18,2),
--STOK SMALLINT,
--DURUM BIT,
--KATEGORI INT
--)

--CREATE TABLE TBLSATIS
--(
--SATISID INT PRIMARY KEY IDENTITY(1,1),
--MUSTERI INT,
--URUN INT,
--TARIH DATE
--)

--ÖRNEK VERÝ GÝRÝÞLERÝ
--UPDATE TBLSTOK SET TOPLAMURUN = (SELECT COUNT(*) FROM TBLURUN)

--TETÝKLEYÝCÝ OLUÞTURULMASI
--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--UPDATE TBLSTOK SET TOPLAMURUN += 1

--UPDATE TBLSTOK SET TOPLAMURUN = (SELECT SUM(STOK) FROM TBLURUN)

--DROP TRIGGER ARTTIR

--DEÐÝÞKEN ÝLE PARAMETRELÝ TETÝKLEYÝCÝ KULLANIMI
--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI = STOK FROM inserted
--UPDATE TBLSTOK SET TOPLAMURUN += @STOKSAYI

--TETÝKLEYÝCÝNÝN STOKLARI DÜÞÜRMESÝ
--CREATE TRIGGER AZALT
--ON TBLURUN
--AFTER DELETE
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI = STOK FROM deleted
--UPDATE TBLSTOK SET TOPLAMURUN -= @STOKSAYI

--INSERT INTO TBLURUN (AD,STOK) VALUES ('MIXER',80)

--ÖDEV: ÜRÜN TABLOSUNUN AYNISINI BÝR DAHA OLUÞTURUN. ÜRÜNÜN ADI, STOK SAYISI, ALIÞ VE SATIÞ FÝYATI OLSUN.
--ÜRÜN TABLOSUNDAN BÝR ÜRÜN SÝLDÝÐÝNÝZ AN O ÜRÜN YENÝ OLUÞTURDUÐUNUZ TABLOYA KAYDOLSUN AMA AYNI ZAMANDA BURADAN DA SÝLÝNSÝN.
--CREATE TRIGGER YEDEKLE
--ON TBLURUN
--AFTER DELETE
--AS
--DECLARE @AD VARCHAR(20),@STOKSAYI INT, @ALISFIYAT DECIMAL(18,2), @SATISFIYAT DECIMAL(18,2)
--SELECT @AD = AD, @STOKSAYI = STOK, @ALISFIYAT = ALISFIYAT, @SATISFIYAT = SATISFIYAT FROM deleted
--INSERT INTO TBLURUNYEDEK (AD,STOK,ALISFIYAT,SATISFIYAT) VALUES (@AD,@STOKSAYI,@ALISFIYAT,@SATISFIYAT)